vim.api.nvim_create_user_command('InlayHints', function()
  local enabled = not vim.lsp.inlay_hint.is_enabled({})
  vim.lsp.inlay_hint.enable(enabled)
  vim.notify("Inlay hints: " .. (enabled and " on" or "off"))
end, { desc = 'Toggle inlay hints' })
