include ./theme.conf

font_family      family="GeistMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0

mouse_hide_wait 3.0

sync_to_monitor yes

enable_audio_bell no
visual_bell_duration 0.2
bell_on_tab "🔔 "

macos_option_as_alt left
# clear_all_shortcuts yes
