-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A5A",
  mode = "2240x1400@60.00",
  position = "529x630",
  scale = 1,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL G3223Q G76R3H3",
  mode = "3840x2160@119.88",
  position = "-192x-1530",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
